apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    – ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
